version: '3.1'

services:
  backend:
    platform: linux/x86_64
    build: ./
    container_name: backend
    working_dir: /app-backend
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 6060:6060
      - 5555:5555
    volumes:
      - ./:/app-backend
    env_file:
      - .env
    networks:
      - srcnet
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.26
    container_name: mysqldb
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - srcnet
networks:
  srcnet:
    driver: bridge