version: '3.1'

services:
  node:
    platform: linux/x86_64
    image: node:14.17.6
    container_name: node
    command: npm run dev
    working_dir: /home/app
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 6060:6060
    volumes:
      - ./:/home/app
    networks:
      - net1
    depends_on:
      - mysqldb
    env_file:
      - .env
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0.26
    container_name: mysqldb
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - net1
networks:
  net1:
    driver: bridge